---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-role-graylog-collector
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - cd ansible-role-graylog-collector

script:
  # Run tests.
  - molecule test

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
