---
# file: tasks/main.yml

# Variable configuration.
- import_tasks: variables.yml

# Setup/install tasks.
- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Setup/install tasks.
- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: "Configure sidecar"
  template:
    src: sidecar.yml
    dest: "{{ sidecar_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart graylog sidecar
    - activate graylog-sidecar service
  become: true
